### ISSUE TITLE
Command Line REPL doesn't like simple module names?

### ISSUE THREAD

**Issue by Ingo60** [Frege/frege-repl#10]
Here is a transcript:

    frege> :load /home/ingo/frege/examples/CommandLineClock.fr
    Module examples.CommandLineClock
    frege> :browse examples.CommandLineClock
    data type Date :: native java.util.Date
    value current :: IO String
    value main :: [String] -> IO ()
    frege> current
    [ERROR: 4]: can't resolve `current`, did you mean `curry` perhaps?
    frege> import examples.CommandLineClock
    frege> current
    "Mon Oct 27 21:12:35 CET 2014"

So far, so good. 
But then:

    frege> :load /home/ingo/frege/frege/Scrap.fr
    Module Scrap
    frege> :browse Scrap
    function toDouble :: Integral a => a -> Double
    value foo :: [Double]
    frege> import Scrap
    frege> foo
    [ERROR: 1]: The import Scrap cannot be resolved

To reproduce, try to load and import a module with a simple name, and then use definitions from it.

**Comment by mmhelloworld** [comment]
Sorry, I am not sure how I missed your comment. Yes, this issue is fixed.
