### ISSUE TITLE
Recognize -comments and -O/-inline options.

### ISSUE THREAD

**Issue by Ingo60** [Frege/frege-repl#17]
I use the REPL often to check the code generated for some silly expressions. However, the REPL produces only uncommented, un-optimized code.

It would be great if we could give the -comments and -inline options on the command line.

Even better would be to have a `:set` command for switching various flags on and off. (Of course, crucial flags like -j, -make and so on should not be settable).

**Comment by mmhelloworld** [comment]
I have taken an initial stab at supporting the following parameters. These options can now be set or unset through `:set` and `:unset` commands respectively.

`v`
`hints`
`nowarn`
`inline`
`O`
`comments`
`ascii` 
`greek` 
`fraktur` 
`latin`
