### ISSUE TITLE
earlier hints and warnings are repeated

### ISSUE THREAD

**Issue by Ingo60** [Frege/frege-repl#18]
I think this was not so in previous versions:

    Welcome to Frege 3.22.367-g2737683 (Oracle Corporation OpenJDK Server VM, 1.8.0_40-internal)

    frege> import Data.Monoid
    [HINT: 3]: H <console>.fr:3: unused import of Data.Monoid as Monoid

    frege> 5 == true
    [ERROR: 4]: E <console>.fr:4: Bool is not an instance of Num
    [HINT: 2]: H <console>.fr:2: unused import of Data.Monoid as Monoid

    frege> 5 == 4
    false

    frege> true == "why?"
    [ERROR: 4]: E <console>.fr:4: type error in  expression "why?"
        type is   String
        used as   Bool
    [HINT: 2]: H <console>.fr:2: unused import of Data.Monoid as Monoid

The same happens with other warnings and hints.

**Comment by mmhelloworld** [comment]
Yes, these repeated warnings are quite annoying. I guess, I have to filter by line number.

**Comment by mmhelloworld** [comment]
This issue has been fixed.
