### ISSUE TITLE
distinguish program arguments from system properties

### ISSUE THREAD

**Issue by Dierk** [Frege/frege-repl#20]
ATM, program arguments like terminal=gui appear in the syntax of system properties (-Dterminal=gui) but cannot be set as system arguments. They must be set in the place where program arguments appear - but in the syntax of system arguments. That is surprising.

I'd suggest to make it a usual program argument.

**Comment by mmhelloworld** [comment]
Now the terminal parameter can be passed with `-terminal` (For example, `-terminal gui`).
