### ISSUE TITLE
First official release

### ISSUE THREAD

**Issue by mperry** [Frege/frege-repl#27]
The frege repl has not had an official release, the current version is 1.1.1-SNAPSHOT.  Should this be released as 1.1 and any further changes done to a 1.2-SNAPSHOT version?

**Comment by mperry** [comment]
@mmhelloworld ping.

**Comment by mmhelloworld** [comment]
Since the current version is 1.1.1-SNAPSHOT, we can release that as 1.1.1 and have the next version as 1.2-SNAPSHOT as you said.

**Comment by mperry** [comment]
Yes, sorry about the typo.  I meant 1.1.1, not 1.1.

**Comment by mperry** [comment]
This now has numerous official releases and can be closed.
