### ISSUE TITLE
SNAPSHOT-1.2.0 commands not working

### ISSUE THREAD

**Issue by Ingo60** [Frege/frege-repl#34]
The following does not work:

    import Test.QuickCheck
    :browse QuickCheck

It doesn't show anything. If I do

    x = sample
    :browse

still nothing!

Also

    :help 
    At the prompt, you can enter Frege code snippets to get them evaluated.^JThe output or compilation errors ...

prints a long line with ^J instead of newlines. However, `println "a\nb"` prints the lines correctly.

**Comment by Ingo60** [comment]
It seems that the :browse only doesn't show links. (It so happens that Test.QuickCheck does not define anything of its own, it just re-eexports symbols from sub-modules.)
I think at least :browse without module name should show all symbols that one can use without qualification.

**Comment by mmhelloworld** [comment]
REPL currently filters out aliases. That seems to be the cause for `browse` being not working. I think it should display everything including aliases. 

The newline issue seems to be with JLine as it appears to be from this [code](https://github.com/jline/jline2/blob/master/src/main/java/jline/console/ConsoleReader.java#L3458). I will dig into this.

**Comment by mmhelloworld** [comment]
This has been fixed and the snapshot release has been updated.
