### ISSUE TITLE
Support installation via Homebrew

### ISSUE THREAD

**Issue by netzwerg** [Frege/frege-repl#45]
[Homebrew](http://brew.sh) is "The missing package manager for OS X". It is very popular because it allows for easy/versioned installations.

It would be great to have a package (aka formula) for the frege-repl – any plans?

I have never written a homebrew package before, but it looks quite simple and I would happily give it a shot if you are interested.

**Comment by mmhelloworld** [comment]
> I would happily give it a shot if you are interested.

That would be great. Thanks!

**Comment by netzwerg** [comment]
Excellent – I am almost done with the script.

I am a little confused regarding your release version numbering: Homebrew only accepts formulae with stable releases. Which is your latest stable release? Preferably, I would like to link to a ZIP with binaries (e.g. like the `frege-repl-1.4-SNAPSHOT.zip` you published, but for a non-SNAPSHOT release).

**Comment by hamnis** [comment]
This would be great to have.

**Comment by neutric** [comment]
`frege-repl` [was added](https://github.com/Homebrew/homebrew-core/pull/1088) to Homebrew quite a while ago, so this can be closed.

**Comment by netzwerg** [comment]
Yep, thanks for heads-up – I will close it.
