### ISSUE TITLE
generated fregei script does not work

### ISSUE THREAD

**Issue by Ingo60** [Frege/frege-repl#46]
After

    ./gradlew install

I try to run the fregei script, but it fails to find the main class.

    Error: Could not find or load main class frege.repl.FregeRepl 

It generates the following command-line to execute:

    java -classpath /home/ingo/Frege/frege-repl/frege-repl-core/build/lib/frege-repl-core-1.2.1-SNAPSHOT.jar:...

but there is no directory `build/lib`, only `build/libs`

But even if I make a symbolic link from lib to libs, it still doesn't run. The `build/libs` directory contains only:

    ingo@freguntu:~/Frege/frege-repl$ ls -l frege-repl-core/build/libs
    total 540
    -rw-rw-r-- 1 ingo ingo 543981 Okt 31 11:16 frege-repl-core-1.2.1-SNAPSHOT.jar
    -rw-rw-r-- 1 ingo ingo    261 Okt 31 11:16 frege-repl-core-1.2.1-SNAPSHOT-javadoc.jar
    -rw-rw-r-- 1 ingo ingo    639 Okt 31 11:16 frege-repl-core-1.2.1-SNAPSHOT-sources.jar

but the generated command expects many more, like jline.jar, ecc.jar 

Note that I can run

    ./gradlew -q run

Not to offend anyone, but I really hate it to run everything through gradle. A build tool should **build** something I can run **without** the build tool, right?

(I did this to give the REPL more stack size. I have no idea how to tell ./gradle to do this.)

**Comment by Dierk** [comment]
you can of course just build without running. "compile" for only compiling or "dist" to make a self-running distribution including all dependencies.
It is only so that often one builds for the purpose of running (or running the tests) in which case it is just convenient to do that in one go with "run" task of the application plugin

**Comment by Ingo60** [comment]
What I did now is to intercept the java command it uses with `./gradlew -q run`

However, it is still strange that the generated script doesn't work.

**Comment by mmhelloworld** [comment]
By default, when we run `./gradlew install`, gradle only generates archive not a distribution directory with all the necessary jars and the scripts. The script you were trying to run was just copied to create an archive so it wouldn't have the necessary setup. We have two options:

1. Unzip the generated archive into some folder and then run the script extracted from it. The archive will be available in `frege-repl-core/build/distributions/` when we run `gradlew install`
2. The better approach is to call the task `installDist` to create a directory with all the jars and the scripts.

```
frege-repl$ ./gradlew installDist

frege-repl$ ls frege-repl-core/build/install/frege-repl/
bin  lib

frege-repl$  frege-repl-core/build/install/frege-repl/bin/frege-repl
Welcome to Frege 3.23.370-g898bc8c (Oracle Corporation Java HotSpot(TM) 64-Bit Server VM, 1.8.0_25)

frege>
```

By the way, in the latest version, I changed the script name to be `frege-repl` from `fregei` to avoid confusion.

**Comment by mmhelloworld** [comment]
I am closing this issue now. If the options described above do not work, please reopen.
