### ISSUE TITLE
Integration with Sbt Frege

### ISSUE THREAD

**Issue by dk14** [Frege/frege-repl#49]
Would be great to have an integration with this plugin:
https://github.com/earldouglas/sbt-frege

**Comment by mmhelloworld** [comment]
Happy to accept pull requests as I am not much familiar with Sbt.

**Comment by mmhelloworld** [comment]
Actually this should be addressed in the sbt-frege plugin so I don't think it belongs here.

**Comment by dk14** [comment]
Agree, I thought that you're not publishing the REPL to the sonatype, but now I found the link.
Anyway, you could help providing minimum set of jars needed to launch the REPL. As I understand the main class is `frege.repl.FregeRepl`

P.S. Just a cross link to the mirrored issue https://github.com/earldouglas/sbt-frege/issues/34
