### ISSUE TITLE
frege-repl-1.4-SNAPSHOT.zip checksum changed

### ISSUE THREAD

**Issue by neutric** [Frege/frege-repl#51]
When `frege-repl` was [added to Homebrew](https://github.com/Homebrew/homebrew-core/pull/1088) in May 2016, the sha256 for `frege-repl-1.4-SNAPSHOT.zip` was `2cf1c2a8f7b64c9d70b21fbfd25b2af3f5e3bebe3662f724afd435d01bddafec`, but seems to be `2ca5f13bc5efaf8515381e8cdf99b4d4017264a462a30366a873cb54cc4f4640` now, which means the Homebrew installation fails with

```
Error: SHA256 mismatch
Expected: 2cf1c2a8f7b64c9d70b21fbfd25b2af3f5e3bebe3662f724afd435d01bddafec
Actual: 2ca5f13bc5efaf8515381e8cdf99b4d4017264a462a30366a873cb54cc4f4640
```

I suppose this is due to the snapshot being updated in place after the addition to Homebrew. Can you confirm this and the correctness of the checksum?

**Comment by neutric** [comment]
@Dierk Care to comment?

**Comment by Dierk** [comment]
I'm happy to help, but I wasn't involved in the homebrew packaging nor do I have any expertise in that area. 
Hope someone else can chime in.

**Comment by neutric** [comment]
@Dierk Sorry if I wasn't clear enough, but my question was regarding the file marked as `Latest release` on https://github.com/Frege/frege-repl/releases.

**Comment by mmhelloworld** [comment]
Hi @neutric ,

I remember updating the snapshot. I think it is to fix this bug https://github.com/Frege/frege/issues/292.

**Comment by neutric** [comment]
@mmhelloworld Hello! :D Thanks for your confirmation, that means we can go ahead and update the checksum.

For the future: please consider not reusing the same tag when uploading a new release so that projects like Homebrew, which rely on checksums, do not break out of the blue. Adding e.g. a date to it would suffice.

**Comment by mmhelloworld** [comment]
Sorry for the confusion! If I understand this correctly, going forward we will add a date to the zip file name. Thanks for following up on this.

**Comment by neutric** [comment]
No worries. And that would be helpful. Thanks!
